[project]
name = "hw4-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopy>=2.4.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
